In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [4]:
df = np.round(pd.read_csv('50_Startups.csv')[['R&D Spend','Administration','Marketing Spend', 'Profit']]/10000)
np.random.seed(6)
df = df.sample(5)
df

    R&D Spend  Administration  Marketing Spend  Profit
49        0.0            12.0              5.0     1.0
40        3.0            12.0             17.0     8.0
38        2.0             7.0             19.0     8.0
23        7.0            11.0             30.0    11.0
7        13.0            15.0             32.0    16.0

In [5]:
df = df.drop('Profit', axis=1)
df

    R&D Spend  Administration  Marketing Spend
49        0.0            12.0              5.0
40        3.0            12.0             17.0
38        2.0             7.0             19.0
23        7.0            11.0             30.0
7        13.0            15.0             32.0

In [6]:
df.iloc[1,0] = np.nan
df.iloc[2,2] = np.nan
df.iloc[3,1] = np.nan
df

    R&D Spend  Administration  Marketing Spend
49        0.0            12.0              5.0
40        NaN            12.0             17.0
38        2.0             7.0              NaN
23        7.0             NaN             30.0
7        13.0            15.0             32.0

In [7]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [9]:
imputer = IterativeImputer(max_iter=10, random_state=0) # Initialize IterativeImputer
df_imputed_array = imputer.fit_transform(df) # Apply imputer
df_imputed = pd.DataFrame(df_imputed_array, columns=df.columns, index=df.index) # Convert to DataFrame
print("Original DataFrame with NaN values:")
print(df)
print("\nImputed DataFrame:")
print(df_imputed)

Original DataFrame with NaN values:
    R&D Spend  Administration  Marketing Spend
49        0.0            12.0              5.0
40        NaN            12.0             17.0
38        2.0             7.0              NaN
23        7.0             NaN             30.0
7        13.0            15.0             32.0

Imputed DataFrame:
    R&D Spend  Administration  Marketing Spend
49   0.000000       12.000000         5.000000
40   4.621113       12.000000        17.000000
38   2.000000        7.000000        21.455889
23   7.000000        8.970924        30.000000
7   13.000000       15.000000        32.000000