In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [5]:
df = pd.read_csv("train.csv")[['Age','Pclass','SibSp','Parch','Survived']]
df

      Age  Pclass  SibSp  Parch  Survived
0    22.0       3      1      0         0
1    38.0       1      1      0         1
2    26.0       3      0      0         1
3    35.0       1      1      0         1
4    35.0       3      0      0         0
..    ...     ...    ...    ...       ...
886  27.0       2      0      0         0
887  19.0       1      0      0         1
888   NaN       3      1      2         0
889  26.0       1      0      0         1
890  32.0       3      0      0         0

[891 rows x 5 columns]

In [7]:
df.dropna(inplace=True)

In [8]:
X = df.drop('Survived', axis=1)
y = df['Survived']

In [10]:
np.mean(cross_val_score(LogisticRegression(), X, y, scoring='accuracy', cv=20))

np.float64(0.6921165884194054)

# Apply Feature Construction

In [11]:
X['Family_Size'] = X['SibSp'] + X['Parch'] + 1

In [12]:
def Resize(num):
  if num == 1:
    return 0
  elif num > 1 and num <= 4:
    return 1
  else:
    return 2

In [13]:
X['Family_Size'] = X['Family_Size'].apply(Resize)

In [14]:
X

      Age  Pclass  SibSp  Parch  Family_Size
0    22.0       3      1      0            1
1    38.0       1      1      0            1
2    26.0       3      0      0            0
3    35.0       1      1      0            1
4    35.0       3      0      0            0
..    ...     ...    ...    ...          ...
885  39.0       3      0      5            2
886  27.0       2      0      0            0
887  19.0       1      0      0            0
889  26.0       1      0      0            0
890  32.0       3      0      0            0

[714 rows x 5 columns]

In [15]:
X.drop(['SibSp','Parch'], axis=1, inplace=True)

In [19]:
np.mean(cross_val_score(LogisticRegression(), X, y, scoring='accuracy', cv=20))

np.float64(0.7003174603174602)

# Feature Splitting